### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by Rishat-F** [Rishat-F/khl#2]
Logo in README and PyPI description will make repository (package) more attractive.
No need complex logo, just a hockey puck with the inscription "khl".

**Comment by alvatip** [comment]
Hi,
Here is something that might suit you, 
If you need, I can also provide the original SVG file or make modification to it :wink: 

![KHL_logo](https://user-images.githubusercontent.com/84344248/214621584-bb5fe7fb-e785-4b02-b045-a4e6b7b81fc7.png)

**Comment by Rishat-F** [comment]
Hello, @alvatip! Looks nice, but it is too motley. More minimalistic would be enough, i think.
I have made this png layout with puck picture:
![](https://raw.githubusercontent.com/Rishat-F/khl/docs/data/logo.png)
and want to experiment with different fonts to write "khl" on the puck. You are welcome too if you want - post your examples here and i post mine.

**Comment by Rishat-F** [comment]
![](https://raw.githubusercontent.com/Rishat-F/khl/docs/data/logo_5.png)
